sudo: required

language: python

python:
  - 2.6
  - 2.7

services:
  - docker

before_install:
  - docker build -t asibin/networktoolsapi .
script:
  - docker run asibin/networktoolsapi /bin/sh -c python tests/tests.py'